#:kivy 2.2.1

#:import Factory kivy.factory.Factory

<MainMenuButton@Button>:
    font_name: 'Audiowide-Regular'
    font_size: 30
    bold: True
    size_hint: .65, .16
    pos_hint: {'center_x': .5}
    padding: 10, 20
    on_press: app.root.prev_screen = app.root.current

<BackButton@Button>:
    font_size: 30
    bold: True
    text: "<"
    size_hint: None, None
    size: self.texture_size
    text_size: 40, 40
    halign: 'center'
    valign: 'middle'
    padding: 0, 0, 0, 5
    pos_hint: {'left': 1, 'center_y': .5}
    on_release: app.root.current = app.root.prev_screen

<TitleBar@BoxLayout>:
    page_title: page_title
    title_txt: ''

    canvas:
        Color:
            rgba: 0, 0, 1, 1
        Rectangle:
            size: self.size
            pos: self.pos
    padding: 10
    orientation: 'horizontal'
    size_hint: 1, None
    height: 60
    pos_hint: {'top': 1}

    BackButton:

    Label:
        id: page_title
        font_name: 'Audiowide-Regular'
        font_size: 30
        bold: True
        text: root.title_txt

<NewProjectPopup>:
    project_name: self.ids.input.text

    size_hint: None, None
    size: 360, 180

    RelativeLayout:
        canvas:
            Color:
                rgba: 1, .5, .8, 1
            Rectangle:
                size: self.size

        size_hint: None, None
        size: 360, 180

        Label:
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': .5, 'top': .92}

            font_size: 24
            padding: 10
            bold: True
            text: 'Create Project'

        TextInput:
            id: input
            multiline: False
            focus: True
            write_tab: False

            cursor_width: '8sp'
            font_size: 18
            text: 'New Project'

            size_hint: None, None
            width: 280
            height: self.minimum_height
            pos_hint: {'center_x': .5, 'center_y': .5}

        Button:
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': .12, 'center_y': .15}

            font_size: 18
            padding: 6
            bold: True
            text: 'Cancel'

            on_release: root.dismiss(animation=False)

        Button:
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': .88, 'center_y': .15}

            font_size: 18
            padding: 6
            bold: True
            text: 'Create'

            on_release: app.add_project(root.project_name); root.dismiss(animation=False)

<ProjectEntry>:
    size_hint: 1, None
    pos_hint: {'center_x': .5}
    height: 100

    Button:
        text: root.project_ref.name_
        size_hint: 1, 1
        on_press: app.root.prev_screen = app.root.current
        on_release: app.open_project(root.project_ref)

    Button:
        text: "X"
        size_hint: None, None
        size: 20, 20
        pos_hint: {'center_x': .9, 'center_y': .5}
        on_release: app.remove_project(root.project_ref.name_, root)

<ProjectPageListNode>:
    font_size: 16

<NewCategoryPopup>:
    size_hint: None, None
    size: 360, 180

    RelativeLayout:
        canvas:
            Color:
                rgba: 1, .5, .8, 1
            Rectangle:
                size: self.size

        size_hint: None, None
        size: 360, 180

        Label:
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': .5, 'top': .92}

            font_size: 24
            padding: 10
            bold: True
            text: 'Add Category'

        TextInput:
            id: input
            multiline: False
            focus: True
            write_tab: False

            cursor_width: '8sp'
            font_size: 18
            text: 'New Category'

            size_hint: None, None
            width: 280
            height: self.minimum_height
            pos_hint: {'center_x': .5, 'center_y': .5}

        Button:
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': .12, 'center_y': .15}

            font_size: 18
            padding: 6
            bold: True
            text: 'Cancel'

            on_release: root.dismiss(animation=False)

        Button:
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': .88, 'center_y': .15}

            font_size: 18
            padding: 6
            bold: True
            text: 'Create'

            on_release: app.create_category(root.ids.input.text); root.dismiss(animation=False)

<CodexRoot>:
    current_project: self.current_project

    Screen:
        id: mainmenu_screen
        name: 'mainmenu_screen'
        canvas:
            Color:
                rgba: 1, 1, 0, 1
            Rectangle:
                size: self.size
                pos: self.pos

        BoxLayout:
            id: mainmenu
            padding: 0, 0, 0, 75
            spacing: 10
            size_hint: None, None
            width: 400 + ((root.width-800)/root.width)*400
            height: 500 + ((root.height-600)/root.height)*400
            pos_hint: {'center_x': .5, 'center_y': .5}

            canvas:
                Color:
                    rgba: 0, 0.5, 0.4, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            orientation: 'vertical'

            Label:
                font_name: 'Audiowide-Regular'
                font_size: 60
                text: 'The Codex'
                color: 1, 0, 0, 1
                size_hint: None, .36
                pos_hint: {'center_x': 0.5}

            MainMenuButton:
                text: 'Open Last'

            MainMenuButton:
                text: 'Open Project'
                on_release: root.current = 'project_browser'

            MainMenuButton:
                text: 'New Project'
                on_release: Factory.NewProjectPopup().open(animation=False)

            MainMenuButton:
                text: 'Settings'

    Screen:
        id: project_browser
        name: 'project_browser'
        canvas:
            Color:
                rgba: .8, .5, 0, 1
            Rectangle:
                size: self.size
                pos: self.pos

        TitleBar:
            title_txt: 'Project Browser'

        ScrollView:
            size_hint: 1, None
            height: root.height - 60
            do_scroll_x: False
            always_overscroll: False

            BoxLayout:
                id: project_list
                canvas:
                    Color:
                        rgba: 1, 0, 1, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos

                orientation: 'vertical'
                padding: (root.width * .08), (root.height * .02)
                size_hint_y: None
                height: self.minimum_height

    Screen:
        id: project_screen
        project_name: ''

        name: 'project_screen'
        canvas:
            Color:
                rgba: 1, .5, .6, 1
            Rectangle:
                size: self.size
                pos: self.pos

        on_pre_enter: app.load_page_tree(); root.ids.project_screen.project_name=root.current_project.name_
        on_leave: app.root.prev_screen = 'mainmenu_screen'

        TitleBar:
            title_txt: root.ids.project_screen.project_name

            Button:
                font_size: 8
                bold: True
                text: "add page"
                size_hint: None, None
                width: self.texture_size[0]
                height: 40
                halign: 'center'
                valign: 'middle'
                padding: 0, 0, 0, 5
                pos_hint: {'center_y': .5}

            Button:
                font_size: 8
                bold: True
                text: "add category"
                size_hint: None, None
                width: self.texture_size[0]
                height: 40
                halign: 'center'
                valign: 'middle'
                padding: 0, 0, 0, 5
                pos_hint: {'center_y': .5}
                on_release: Factory.NewCategoryPopup().open(animation=False)

        RelativeLayout:
            canvas:
                Color:
                    rgba: .3, 0, .1, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            size_hint: 1, None
            height: root.height - 60

            ScrollView:
                size_hint_x: (3/19) if (root.width >= 950) else 0
                do_scroll_x: False
                always_overscroll: False

                TreeView:
                    id: page_tree
                    root_options: {'text': root.ids.project_screen.project_name, 'font_size': 16, 'no_selection': True}

                    canvas:
                        Color:
                            rgba: 1, 0, 0, 1
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    size_hint_y: None
                    height: self.minimum_height


            ContentPane:
                id: content_pane
                size_hint_x: (1-(3/19)) if (root.width >= 950) else 1
                pos_hint: {'x': (root.ids.page_tree.width/root.width)}
                text: root.ids.page_tree.selected_node.page_.text_ if isinstance(root.ids.page_tree.selected_node, kivy.uix.treeview.TreeViewNode) else ''
